CREATE DATABASE IF NOT EXISTS mystudio;

USE mystudio;

CREATE TABLE IF NOT EXISTS STYLES {
    id INT(11) NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    style_name VARCHAR(12) NOT NULL,
}

CREATE TABLE IF NOT EXISTS ARTISTS {
    id INT(11) AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
    artist_name varchar(12) NOT NULL,
    cat ENUM('amateur','pro') NOT NULL,
}

CREATE TABLE IF NOT EXISTS ALBUMS {
    id INT(11)NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    album_name varchar(45) NOT NULL,
    album_cover BLOB,
	release_date YEAR,
}

CREATE TABLE IF NOT EXISTS USERS {
    id INT(11) AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
    username varchar(12) NOT NULL,
    pw CHAR(41) NOT NULL,
    cat ENUM('artiste','utilisateur') NOT NULL,
}

CREATE TABLE IF NOT EXISTS MUSICS {
    id INT(11) AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
    title VARCHAR(45) NOT NULL,
    featuring VARCHAR(45) NOT NULL,
    nb_listening INT(11) NULL,
    lyrics BLOB,
    trans BLOB,
    music BLOB,
    style SMALLINT NOT NULL,
    album INT(11),
    artist INT(11),
	CONSTRAINT fk_album_has_MUSICS
		FOREIGN KEY (album)
		REFERENCES mystudio.ALBUMS (album_name)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT fk_artist_has_MUSICS
		FOREIGN KEY (artist)
		REFERENCES mystudio.ARTISTS (artist_name)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT fk_style_has_MUSICS
		FOREIGN KEY (style)
		REFERENCES mystudio.STYLES (style_name)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
}

CREATE TABLE IF NOT EXISTS PLAYLISTS {
    id int(11) AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
    play_title VARCHAR(45),
    birthdate DATE,
    users INT(11),
CONSTRAINT fk_users_has_GENRES_PLAYLIST
		FOREIGN KEY (users)
		REFERENCES mystudio.USERS (username)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
}

CREATE TABLE IF NOT EXISTS REGISTERED_IN {
    id INT(11) AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
    music INT(11),
    playlist INT(11),
	CONSTRAINT fk_music_has_REGISTERED_IN
		FOREIGN KEY (music)
		REFERENCES mystudio.MUSICS (title)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT fk_playlist_has_REGISTERED_IN
		FOREIGN KEY (playlist)
		REFERENCES mystudio.PLAYLISTS (playlist_name)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
}